image: python:3.9

stages:
  - lint
  - test

lint:
  stage: lint
  before_script:
    - pip install flake8
  script:
    - flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

# Test placeholder (if there were unit tests)
# test:
#   stage: test
#   script:
#     - pip install -r requirements.txt
#     - pytest tests/
